source 'https://github.com/CocoaPods/Specs.git'

target 'BTLabel', :exclusive => true do
  pod "BTLabel", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "BTLabel", :path => "../"

  
end
